### ISSUE TITLE
PHP Syntax errors in xml files

### ISSUE THREAD

**Issue by Hexmage** [magento/magento-coding-standard#265]
### Preconditions

1.  magento/magento-coding-standard v9
2. A magento module that has an xml file that starts with `<?xml version="1.0" ?>`

### Steps to reproduce

1. run  `bin/phpcs ./ --standard=Magento2 --severity=10`

### Expected result

1. Nothing module passes the test

### Actual result

1.
```
FILE: /opt/atlassian/pipelines/agent/build/etc/module.xml
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | PHP syntax error: syntax error, unexpected 'version'
   |       | (T_STRING)
----------------------------------------------------------------------
```
```
FILE: /opt/atlassian/pipelines/agent/build/etc/di.xml
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | PHP syntax error: syntax error, unexpected 'version'
   |       | (T_STRING)
----------------------------------------------------------------------
```

This bug got introduced in v9 because our pipelines were running v8 yesterday and didn't have this issue at the time.

**Comment by ihor-sviziev** [comment]
@sivaschenko, could you set the high priority for this issue?

**Comment by eliseacornejo** [comment]
Hi, I am trying to recreate this issue, with a xml file that starts with <?xml version="1.0" ?> but in my case I am not able to recreate this. Could you please @Hexmage give me more details, on how and when are you having this? Are you using the ruleset from magento-coding-standard or do you have your own ruleset?

**Comment by Hexmage** [comment]
@eliseacornejo 
This is the exact yml I was using. It was added to all our module repositories, so not a full magento installation. Back then the lastest version of magento-coding-standard was v9.

```
options:
  docker: true
pipelines:
  default:
    - step:
        max-time: 10
        name: Static Code Scan
        image: experiusnl/magento-2-docker-pipeline-image-apache-php7.3
        caches:
          - composer
          - docker
        script:
          - mkdir -p var/phpscan
          - composer require phpmd/phpmd magento/magento-coding-standard squizlabs/php_codesniffer --no-interaction -d ./var/phpscan
          - ./var/phpscan/vendor/bin/phpcs --config-set installed_paths var/phpscan/vendor/magento/magento-coding-standard
          - ./var/phpscan/vendor/bin/phpmd ./ text unusedcode --exclude var/
          - ./var/phpscan/vendor/bin/phpcs ./ --ignore=./var/** --standard=PSR2 --severity=6
          - ./var/phpscan/vendor/bin/phpcs ./ --ignore=./var/** --standard=Magento2 --severity=10
```
The error occurred in the last step.
